# Generated by Django 5.1.3 on 2024-12-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_user'),
        ('program', '0001_initial'),
        ('workouts', '0003_alter_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='meals',
            field=models.ManyToManyField(blank=True, to='meals.meal'),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='workouts',
            field=models.ManyToManyField(blank=True, to='workouts.workout'),
        ),
    ]
