# Generated by Django 5.1.3 on 2024-12-09 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0002_meal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('make_public', models.BooleanField(default=False)),
                ('afternoon_snack', models.ManyToManyField(blank=True, related_name='afternoon_snack_meal_plans', to='meals.meal')),
                ('breakfast', models.ManyToManyField(blank=True, related_name='breakfast_meal_plans', to='meals.meal')),
                ('desserts', models.ManyToManyField(blank=True, related_name='dessert_meal_plans', to='meals.meal')),
                ('dinner', models.ManyToManyField(blank=True, related_name='dinner_meal_plans', to='meals.meal')),
                ('lunch', models.ManyToManyField(blank=True, related_name='lunch_meal_plans', to='meals.meal')),
                ('morning_snack', models.ManyToManyField(blank=True, related_name='morning_snack_meal_plans', to='meals.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
