# Generated by Django 5.1.3 on 2024-12-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='plan_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
